### ISSUE TITLE
Test the documentation example

### ISSUE THREAD

**Issue by dtolnay** [taiki-e/easytime#4]
The second example in lib.rs currently renders with a distracting orange warning.

https://docs.rs/easytime/0.1.1/easytime/

![selection_124](https://user-images.githubusercontent.com/1940490/53630179-51972700-3bc4-11e9-9756-4a7278d7357d.png)

**Comment by dtolnay** [comment]
Since it requires nightly, you could have Travis run `cargo test` on nightly and `cargo test --tests` on stable/beta which does not run doc tests.

**Comment by taiki-e** [comment]
Thanks! I will fix it soon.

**Comment by taiki-e** [comment]
Published v0.1.2 which fixes this issue. https://docs.rs/easytime/0.1.2/easytime/
